source 'https://rubygems.org'
gem 'typhoeus'
gem 'mechanize'
gem 'oj'
gem 'tvdbr'
gem 'activerecord', require: 'active_record'
# gem 'pg'
gem 'mysql2'
gem 'dotenv'
gem 'thread', require: 'thread/pool'
